### ISSUE TITLE
Need Image Optimization

### ISSUE THREAD

**Issue by arilukmanp** [ninedotslabs/kampusin#73]
It just beginning and so many large images need to be fetched. Unfortunately, this website has no image fetching optimization right now which will affect to loading time for the end user. Can you imagine if this website has tons of university data and still have no image fetching optimization?

<img width="746" alt="image" src="https://user-images.githubusercontent.com/25118501/195802151-c13ba746-504f-43d7-9b0d-150952afe546.png">

**Comment by arilukmanp** [comment]
Anyway, based on what I've mentioned above, can I work on this issue?

**Comment by mrofisr** [comment]
Yes sure, it's very helpful

**Comment by arilukmanp** [comment]
Hi @mrofisr, won't you assign it to me too?

**Comment by lintangpratama** [comment]
I've assigned it to you @arilukmanp
